const fs = require('fs');

const blog14 = '  {\n    id: "14",\n    slug: "why-study-abroad-applications-get-rejected",\n    title: "Why Study Abroad Applications Get Rejected (And How to Fix It Before You Submit)",\n    excerpt: "Most rejected applications aren\'t rejected for the reasons students think. The actual reason is usually a profile that didn\'t make a clear, distinctive argument for itself.",\n    author: "LiftmyGrade Editorial",\n    authorRole: "Admissions Strategy Team",\n    authorImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=200",\n    category: "Application Strategy",\n    coverImage: "/blog/blog-14.webp",\n    date: "July 3, 2026",\n    content: `\n      <p class="mb-4">Most rejected applications aren\\'t rejected for the reasons students think. The applicant assumes it was their GPA, their GRE, or "they only take students from IITs." The actual reason — visible only to the admissions committee — is usually a profile that didn\\'t make a clear, distinctive argument for itself.</p>\n      <p class="mb-6">This guide breaks down the real rejection patterns we see across Bachelor\\'s, Master\\'s, and PhD applications from India — and what to fix before you submit, not after the email arrives.</p>\n      \n      <h2 class="text-2xl font-bold text-[#1C362B] mt-8 mb-4">The Five Rejection Categories</h2>\n      <p class="mb-4">Rejections cluster into five recognizable patterns. Most failed applications fall into one (sometimes two) of these — rarely "the candidate just wasn\\'t good enough."</p>\n      \n      <figure class="my-8">\n        <img src="/blog/blog-14-1.webp" alt="Application Rejection Patterns" class="w-full rounded-2xl shadow-sm border border-[#EBEFEA] object-cover h-[400px]">\n        <figcaption class="text-sm text-center mt-3 text-gray-500">Common rejection patterns identified by admissions committees</figcaption>\n      </figure>\n\n      <h3 class="text-xl font-bold text-[#1C362B] mb-2">Pattern 1: Profile Mismatch</h3>\n      <p class="mb-6">You can have a strong profile that\\'s still mismatched to the program. A 9.2 CGPA in Mechanical Engineering doesn\\'t help a Computer Science PhD application without demonstrating necessary coursework or research experience. Committees don\\'t admit smart people; they admit smart people who fit their specific cohort needs.</p>\n    `\n  }';

const blog15 = '  {\n    id: "15",\n    slug: "building-an-academic-cv-for-study-abroad",\n    title: "Building an Academic CV for Study Abroad Applications: Structure, Mistakes & Examples",\n    excerpt: "The academic CV is the most underestimated document in a study abroad application. This guide breaks down what an academic CV should look like for Master\\'s and PhD applications.",\n    author: "LiftmyGrade Editorial",\n    authorRole: "Admissions Strategy Team",\n    authorImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=200",\n    category: "Application Strategy",\n    coverImage: "/blog/blog-15.webp",\n    date: "July 3, 2026",\n    content: `\n      <p class="mb-4">The academic CV is the most underestimated document in a study abroad application. Students agonize over their SOP for months, then attach a 1-page corporate-style resume with bullet points about "team collaboration" and "communication skills." The mismatch is jarring — and admissions committees notice.</p>\n      <p class="mb-6">An academic CV isn\\'t a job resume. It serves a different audience, follows different conventions, and emphasizes different signals. This guide breaks down what an academic CV should look like for Master\\'s and PhD applications, and how to build one that actually supports your application.</p>\n      \n      <h2 class="text-2xl font-bold text-[#1C362B] mt-8 mb-4">Academic CV vs Resume: The Critical Distinction</h2>\n      <p class="mb-4">A job resume is a marketing document: it sells you to a hiring manager who will spend 30 seconds scanning it. An academic CV is a credential document: it lists everything you\\'ve done that\\'s relevant to academic evaluation, in a format admissions officers can quickly digest.</p>\n      \n      <figure class="my-8">\n        <img src="/blog/blog-15-1.webp" alt="Academic CV Structure" class="w-full rounded-2xl shadow-sm border border-[#EBEFEA] object-cover h-[400px]">\n        <figcaption class="text-sm text-center mt-3 text-gray-500">The core structure of a winning academic CV</figcaption>\n      </figure>\n    `\n  }';

const blog16 = '  {\n    id: "16",\n    slug: "bachelors-abroad-on-a-budget",\n    title: "Bachelor\\'s Abroad on a Budget: Affordable Countries and Pathways for Indian Students",\n    excerpt: "A Bachelor\\'s degree abroad doesn\\'t have to cost INR 1 crore. This guide breaks down the countries that actually work for budget-conscious Bachelor\\'s applicants.",\n    author: "LiftmyGrade Editorial",\n    authorRole: "Admissions Strategy Team",\n    authorImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=200",\n    category: "Financial Planning",\n    coverImage: "/blog/blog-16.webp",\n    date: "July 3, 2026",\n    content: `\n      <p class="mb-4">A Bachelor\\'s degree abroad doesn\\'t have to cost INR 1 crore. The narrative that\\'s dominated Indian study-abroad conversations — that undergraduate education abroad is reserved for families with vast disposable wealth — quietly skips over the countries where it isn\\'t true.</p>\n      <p class="mb-6">Germany, France, Norway, and parts of Eastern Europe offer Bachelor\\'s degrees that cost INR 15–35 lakh total for three years, including living. That\\'s less than many private engineering colleges in India. The catch: these countries are less marketed, less discussed in WhatsApp study-abroad groups, and require different preparation than the US-UK pipeline.</p>\n      \n      <h2 class="text-2xl font-bold text-[#1C362B] mt-8 mb-4">What "Budget" Actually Means for Bachelor\\'s Abroad</h2>\n      <p class="mb-4">A useful frame: the total 3–4 year cost of a Bachelor\\'s abroad.</p>\n      \n      <figure class="my-8">\n        <img src="/blog/blog-16-1.webp" alt="Budget comparison for Bachelor\\'s Abroad" class="w-full rounded-2xl shadow-sm border border-[#EBEFEA] object-cover h-[400px]">\n        <figcaption class="text-sm text-center mt-3 text-gray-500">Cost comparison between different European countries</figcaption>\n      </figure>\n    `\n  }';

const blog17 = '  {\n    id: "17",\n    slug: "from-student-visa-to-pr",\n    title: "From Student Visa to PR: Settlement Pathways After Master\\'s Abroad in 2026",\n    excerpt: "For a significant share of Indian Master\\'s applicants, the actual goal isn\\'t the degree. It\\'s the country. This guide maps the realistic PR pathways.",\n    author: "LiftmyGrade Editorial",\n    authorRole: "Admissions Strategy Team",\n    authorImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=200",\n    category: "Career & Settlement",\n    coverImage: "/blog/blog-17.webp",\n    date: "July 3, 2026",\n    content: `\n      <p class="mb-4">For a significant share of Indian Master\\'s applicants, the actual goal isn\\'t the degree. It\\'s the country. The Master\\'s is the credentialing event that unlocks a work visa, which unlocks a permanent residency pathway, which unlocks a settled life abroad. Pretending otherwise — in your application or in your planning — is unhelpful.</p>\n      <p class="mb-6">This guide is honest about that motivation. It maps the realistic PR pathways from a Master\\'s degree across the five most relevant destinations for Indian students, what the trade-offs are, and how to plan your Master\\'s choice around your settlement goal.</p>\n      \n      <h2 class="text-2xl font-bold text-[#1C362B] mt-8 mb-4">The Three-Stage Pathway Most Students Follow</h2>\n      <p class="mb-4">Every settlement-focused Master\\'s-to-PR journey breaks into three stages.</p>\n      \n      <figure class="my-8">\n        <img src="/blog/blog-17-1.webp" alt="Student Visa to PR Pathway" class="w-full rounded-2xl shadow-sm border border-[#EBEFEA] object-cover h-[400px]">\n        <figcaption class="text-sm text-center mt-3 text-gray-500">The standard timeline from student visa to permanent residency</figcaption>\n      </figure>\n      \n      <ul class="list-disc pl-6 space-y-2 mb-6">\n        <li>Stage 1 — Student Visa to Post-Study Work Permit. You complete your degree and convert to a work-eligible visa. Each country has different rules, durations, and conditions.</li>\n      </ul>\n    `\n  }';

let blogsTs = fs.readFileSync('data/blogs.ts', 'utf-8');
const toAppend = ',\\n' + blog14 + ',\\n' + blog15 + ',\\n' + blog16 + ',\\n' + blog17 + '\\n];';
if (blogsTs.includes('  }\\r\\n];')) {
  blogsTs = blogsTs.replace('  }\\r\\n];', '  }' + toAppend.replace(/\\n/g, '\\r\\n'));
} else {
  blogsTs = blogsTs.replace('  }\\n];', '  }' + toAppend);
}
fs.writeFileSync('data/blogs.ts', blogsTs);
console.log('Appended 14-17 successfully');
